# Generated by Django 5.0.6 on 2024-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='service',
        ),
        migrations.AddField(
            model_name='appointments',
            name='name',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='staff',
            name='service_name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='city',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='mobile',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='registration_id',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='state',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='status',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='vehicle_number',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='bank_id',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='blood_type',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='user_id',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='address',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='category',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='city',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='mobile',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='name',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='state',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='status',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='website',
            field=models.CharField(default=' ', max_length=800),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='address',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='mobile',
            field=models.CharField(default=' ', max_length=15),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='user_id',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='user_username',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='registration_id',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
