# Generated by Django 5.0.6 on 2024-05-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_remove_staff_service_appointments_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='registration_id',
        ),
    ]
