# Generated by Django 5.0.6 on 2024-05-16 18:38

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_remove_ambulance_registration_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStaffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=' ', max_length=500)),
                ('admin_id', models.CharField(default=' ', max_length=500)),
                ('blood_bank_name', models.CharField(default=' ', max_length=500)),
                ('address', models.CharField(default=' ', max_length=500)),
                ('state', models.CharField(default=' ', max_length=100)),
                ('city', models.CharField(default=' ', max_length=100)),
                ('mobile', models.CharField(default=' ', max_length=100)),
                ('email', models.EmailField(default=' ', max_length=254)),
                ('category', models.CharField(default=' ', max_length=100)),
                ('status', models.CharField(default=' ', max_length=100)),
                ('website', models.CharField(default=' ', max_length=800)),
                ('blood_groups', django_mysql.models.ListCharField(models.CharField(max_length=5), max_length=100, size=10)),
                ('date_send', models.DateField()),
                ('request_message', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=' ')),
                ('admin_id', models.CharField(default=' ', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MessageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=' ', max_length=500)),
                ('bank_id', models.CharField(default=' ', max_length=500)),
                ('date_send', models.DateField()),
                ('message', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=' ', max_length=500)),
                ('bank_id', models.CharField(default=' ', max_length=500)),
                ('service', models.CharField(default=' ', max_length=500)),
                ('blood_units', models.CharField(default=' ', max_length=500)),
                ('blood_type', models.CharField(default=' ', max_length=500)),
                ('diseases', models.CharField(default=' ', max_length=500)),
                ('request_message', models.TextField(default=' ')),
            ],
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='date',
            new_name='on_date',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='is_admn',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='hospital_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointments',
            name='blood_units',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='AB_negative_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='AB_positive_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='A_negative_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='A_positive_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='B_negative_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='B_positive_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='O_negative_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='O_positive_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='user_id',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='age',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
