# Generated by Django 5.0.6 on 2024-05-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_addstaffrequest_announcementstaff_messageuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstaffrequest',
            name='AB_negative_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='addstaffrequest',
            name='AB_positive_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='addstaffrequest',
            name='A_negative_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='addstaffrequest',
            name='A_positive_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='addstaffrequest',
            name='B_negative_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='addstaffrequest',
            name='B_positive_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='addstaffrequest',
            name='O_negative_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='addstaffrequest',
            name='O_positive_units',
            field=models.CharField(default='', max_length=10),
        ),
    ]
