# Generated by Django 5.0.6 on 2024-05-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_addstaffrequest_ab_negative_units_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageuser',
            old_name='bank_id',
            new_name='admin_id',
        ),
        migrations.AddField(
            model_name='messageuser',
            name='sent_admin',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='messageuser',
            name='staff_id',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
