# Generated by Django 5.0.6 on 2024-05-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_rename_bank_id_messageuser_admin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='service',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
