# Generated by Django 5.0.6 on 2024-05-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_appointments_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementstaff',
            name='staff_id',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
